modLoader="kotlinforforge"
loaderVersion="${loader_version_range}" 
license="${mod_license}"
[[mods]] 
modId="${mod_id}" 
version="${mod_version}" 
displayName="${mod_name}" 
#logoFile="modular.png" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''

[[mixins]]
config="modular.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies."${mod_id}"]] #optional
modId="neoforge" 
type="required" 
versionRange="${neo_version_range}" 
ordering="NONE"
side="BOTH"
